### PR TITLE
Add build directory to .gitignore

### PR DESCRIPTION
**Pull request by calebissharp**

### CODE REVIEW

**Comment by krasimir** [comment]
Hey,

Thank you for the PR but the idea is that the library is distributed via the files under `lib` folder. So they should exists when downloading the library or just in GitHub. Those are the compiled ES5 compatible files.

P.S.
More about that [here](http://krasimirtsonev.com/blog/article/javascript-library-starter-using-webpack-es6).

**Comment by calebissharp** [comment]
That makes sense. The only problem would be that the library would have to remember to be built before being pushed to GitHub.

**Comment by krasimir** [comment]
Yep, exactly.

**Comment by calebissharp** [comment]
Should this be added to the Readme so that people will know to build it before? Or do you think it would just be common sense.

**Pull request closed without merging**
